### ISSUE TITLE
hasNextPage returns true even if it has reached the last page in useGetInfiniteRequest

### ISSUE THREAD

**Issue by kingsley-sunny** [ventlio-tech/tanstack-query#17]
When i try to get lists of data using the useGetInfinniteRequest, hasNextPage returns true if It has reacted the end of the data 

I believe the error is from this line when contructing the param in the getNextPageParam link :point_down: 
https://github.com/ventlio-tech/tanstack-query/blob/35dc491cf582ea17a3008f162334ab0f4c528774/src/queries/useGetInfiniteRequest.ts#L101C59-L101C59

Tanstack query needs the getNextPageParam function to return a variable or undefined as defined here :point_down: 

![Screenshot from 2023-10-04 04-50-26-1](https://github.com/ventlio-tech/tanstack-query/assets/76210133/5ff1deb2-b600-4e99-87ad-b8a41b988a84)

**Comment by Stancobridge** [comment]
@kingsley-sunny thanks for reporting the error, I will look into it
